name: hri-ds-download
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python==3.10
  - bioconda::p7zip
  - cuda-toolkit
  - gcsfs
  - gsutil
  - google-auth
  - pandas
  - git-lfs
  - tensorflow-datasets
  - regex
  - openpyxl